name: dummyapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  video_player: ^2.2.10
  percent_indicator: ^3.4.0
  provider: ^6.0.2
  
  # Firebase
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/my/welcome.png
    - assets/my/menu_icon.png
    - assets/my/girl.jpg
    - assets/my/funny.mp4

    - assets/surveyicon/business.png
    - assets/surveyicon/food.png
    - assets/surveyicon/health.png
